---
- hosts: your-target-hosts
  become: yes
  tasks:
    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Reboot the server
      reboot:
