---
- name: Get Disk Space Information
  hosts: all
  gather_facts: true

  tasks:
    - name: Gather Facts
      ansible.builtin.setup:
        filter: ansible_mounts

    - name: Get Disk Space Information for each mount point
      ansible.builtin.stat:
        path: "{{ item.mount }}"
      loop: "{{ ansible_mounts }}"
      register: disk_space_output

    - name: Display Disk Space Information
      debug:
        msg: |
          Server: {{ ansible_hostname }}
          Diskspace Info:
          {% for item in disk_space_output.results %}
          - Mount Point: {{ item.item.mount }}
            Total Size: {{ item.stat.size|filesize }}
            Available: {{ item.stat.size_available|filesize }}
            Used Percentage: {{ ((item.stat.size - item.stat.size_available) / item.stat.size) * 100 }}%
          {% endfor %}
