---
- name: Get Disk Space Information
  hosts: all
  gather_facts: true

  tasks:
    - name: Gather Facts
      ansible.builtin.setup:
        filter: ansible_mounts

    - name: Get Main Hard Disk Information
      ansible.builtin.stat:
        path: /
      register: main_disk_output

    - name: Display Main Hard Disk Information
      debug:
        msg: |
          Server: {{ ansible_hostname }}
          Main Hard Disk Info:
          - Mount Point: /
            Total Size: {{ main_disk_output.stat.size | filesizeformat }}
            Available: {{ main_disk_output.stat.size_available | filesizeformat }}
            Used Percentage: {{ ((main_disk_output.stat.size - main_disk_output.stat.size_available) / main_disk_output.stat.size) * 100 }}%
