---
- name: Get Disk Space Information
  hosts: all
  gather_facts: true

  tasks:
    - name: Run df command on /dev/sda3
      ansible.builtin.shell: df /dev/sda3 | awk 'FNR == 2 {printf "%.1f", $4/1024}'
      register: free_space_output
      changed_when: false

    - name: Display Free Space for /dev/sda3
      debug:
        msg: |
          Server: {{ ansible_hostname }}
          Free Space for /dev/sda3: {{ free_space_output.stdout }} GB
