---
- name: Get Disk Space Information
  hosts: all
  gather_facts: true

  tasks:
    - name: Run df command on /dev/sda3
      ansible.builtin.shell: df /dev/sda3
      register: df_output
      changed_when: false

    - name: Extract Disk Space Information
      set_fact:
        df_lines: "{{ df_output.stdout_lines | list }}"
        disk_space_info: "{{ df_lines[1] | trim }}"
      when: df_output.rc == 0 and df_lines | length > 1

    - name: Display Disk Space Information for /dev/sda3
      debug:
        msg: |
          Server: {{ ansible_hostname }}
          Disk Space Info for /dev/sda3: {{ disk_space_info | default('Information not available') }}
