---
- name: Get Disk Space Information
  hosts: your_remote_fedora_servers_group
  gather_facts: true

  tasks:
    - name: Gather Facts
      ansible.builtin.setup:
        filter: ansible_mounts

    - name: Get Main Hard Disk Information
      ansible.builtin.stat:
        path: /
      register: main_disk_output

    - name: Convert Bytes to Human-Readable Format
      set_fact:
        total_size_human: "{{ main_disk_output.stat.size | custom_humanize }}"
        available_size_human: "{{ main_disk_output.stat.size_available | custom_humanize }}"

    - name: Display Main Hard Disk Information
      debug:
        msg: |
          Server: {{ ansible_hostname }}
          Main Hard Disk Info:
          - Mount Point: /
            Total Size: {{ total_size_human }}
            Available: {{ available_size_human }}
            Used Percentage: {{ ((main_disk_output.stat.size - main_disk_output.stat.size_available) / main_disk_output.stat.size) * 100 }}%
