---
- name: Get Disk Space Information
  hosts: all
  gather_facts: true

  tasks:
    - name: Gather Facts
      ansible.builtin.setup:
        filter: ansible_mounts

    - name: Display Disk Space Information
      debug:
        msg: |
          Server: {{ ansible_hostname }}
          Diskspace Info:
          {% for mount in ansible_mounts %}
          - Mount Point: {{ mount.mount }}
            Total Size: {{ mount.size_total }}
            Used: {{ mount.size_used }}
            Available: {{ mount.size_available }}
            Used Percentage: {{ mount.percent_used }}%
          {% endfor %}
