---
- name: Open firewall ports mfor docker swarm
  hosts: your_target_hosts
  gather_facts: yes
  become: yes
  tasks:
    - name: Install firewalld if it's not installed
      package:
        name: firewalld
        state: present

    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open firewall ports
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - 2376/tcp
        - 2377/tcp
        - 7946/tcp
        - 7946/udp
        - 4789/udp
      notify: 
        - Reload firewalld

  handlers:
    - name: Reload firewalld
      command: firewall-cmd --reload
...
