---
- name: Open firewall ports
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    ports:
      - 22/tcp
      - 80/tcp
      - 443/tcp
      - 2375/tcp
      - 2376/tcp
      - 2377/tcp
      - 2377/udp
      - 3000/tcp # whoami
      - 3001/tcp # Grafana
      - 3023/tcp
      - 3024/tcp
      - 3025/tcp
      - 4440/tcp
      - 4441/tcp
      - 4442/tcp
      - 4443/tcp
      - 4444/tcp
      - 4445/tcp
      - 4446/tcp
      - 4447/tcp
      - 4448/tcp
      - 4449/tcp
      - 4450/tcp
      - 4789/udp
      - 5000/tcp
      - 5001/tcp
      - 5432/tcp
      - 6379/tcp
      - 7900/tcp
      - 7946/tcp
      - 7946/udp
      - 8000/tcp
      - 8005/tcp # Uptime-Kuma
      - 8080/tcp # Traefik
      - 8081/tcp
      - 8082/tcp
      - 8083/tcp
      - 8084/tcp
      - 8085/tcp
      - 8086/tcp
      - 8087/tcp
      - 8088/tcp
      - 8089/tcp
      - 8090/tcp
      - 8091/tcp
      - 8092/tcp
      - 8093/tcp
      - 8094/tcp
      - 8095/tcp
      - 8096/tcp
      - 8097/tcp
      - 8098/tcp
      - 8099/tcp
      - 8501/tcp
      - 8502/tcp
      - 8503/tcp
      - 8504/tcp
      - 8601/tcp
      - 8602/tcp
      - 8603/tcp
      - 8604/tcp
      - 9000/tcp # Portainer
      - 9001/tcp
      - 9001/udp
      - 9090/tcp # Fedora SELinux
      - 9100/tcp # Prometheus
      - 9443/tcp # Portainer
  tasks:
    - name: Install firewalld if it's not installed
      package:
        name: firewalld
        state: present

    - name: Open firewall ports
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items: "{{ ports }}"
      notify: 
        - Reload firewalld

    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Reboot the servers
      tags: reboot
      become: yes
      become_method: sudo
      become_user: root
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
    
    - name: Wait for the reboot to complete if there was a change
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 300

  handlers:
    - name: Reload firewalld
      command: firewall-cmd --reload
