---
- name: Open firewall ports
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    ports:
      - 80/tcp
      - 443/tcp
      - 2376/tcp
      - 2377/tcp
      - 3000/tcp
      - 4440/tcp
      - 4441/tcp
      - 4442/tcp
      - 4443/tcp
      - 4444/tcp
      - 4445/tcp
      - 4446/tcp
      - 4447/tcp
      - 4448/tcp
      - 4449/tcp
      - 4450/tcp
      - 4789/udp
      - 5000/tcp
      - 5432/tcp
      - 7946/tcp
      - 7946/udp
      - 8080/tcp
      - 8081/tcp
      - 8082/tcp
      - 8083/tcp
      - 8084/tcp
      - 8085/tcp
      - 8086/tcp
      - 8087/tcp
      - 8088/tcp
      - 8089/tcp
      - 8090/tcp
      - 8091/tcp
      - 8092/tcp
      - 8093/tcp
      - 8094/tcp
      - 8095/tcp
      - 8096/tcp
      - 8097/tcp
      - 8098/tcp
      - 8099/tcp
      - 9000/tcp
  tasks:
    - name: Install firewalld if it's not installed
      package:
        name: firewalld
        state: present

    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open firewall ports
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items: "{{ ports }}"
      notify: 
        - Reload firewalld

  handlers:
    - name: Reload firewalld
      command: firewall-cmd --reload
...
