---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure directory exists
      file:
        path: "/home/robo/docker-volumes/playbook/"
        state: directory

    - name: Add directory to Git safe list
      shell: |
        git config --global --add safe.directory /home/robo/docker-volumes/playbook
      ignore_errors: true

    - name: Clone Git repository
      git:
        repo: 'https://github.com/unord/rpa-stacks.git'
        dest: "/home/robo/docker-volumes/playbook/"
      become: yes
      ignore_errors: yes

    - name: Get list of yml files
      find:
        paths: "/home/robo/docker-volumes/playbook/"
        patterns: '*.yml'
      register: yml_files

    - name: Add Stack to Portainer
      uri:
        url: "http://10.18.225.150:9000/api/stacks?type=1&method=string&endpointId=44287"
        method: POST
        headers:
          Authorization: "Bearer ptr_cMcWCNM8PnDltTKyy489t7PM1QsuDLnDIOmcQc25HTQ="
        body_format: json
        body: 
          Name: "{{ item.path | basename | regex_replace('.yml$', '') }}"
          StackFileContent: "{{ lookup('file', item.path) }}"
      loop: "{{ yml_files.files }}"
