---
- name: Gather uptime information
  hosts: all
  gather_facts: False

  tasks:
    - name: Get uptime
      command: uptime -p
      register: uptime_output

    - name: Display uptime
      debug:
        var: uptime_output.stdout_lines
...
